import { useMemo } from "react";
import { useAuth } from "@/hooks/useAuth";
import { supabase } from "@/integrations/supabase/client";
import { useQuery } from "@tanstack/react-query";

export interface BusinessTerminology {
  // Core entities
  products: string;
  product: string;
  inventory: string;
  customers: string;
  customer: string;
  sales: string;
  sale: string;
  pos: string;
  // Supply chain
  suppliers: string;
  supplier: string;
  purchases: string;
  purchase: string;
  // Finance
  expenses: string;
  invoices: string;
  outstanding: string;
  // Management
  staff: string;
  stores: string;
  store: string;
  // Section labels
  sectionCore: string;
  sectionSalesFinance: string;
  sectionSupplyChain: string;
  // Specific fields
  productCategory: string;
  costPrice: string;
  sellingPrice: string;
  inStock: string;
  barcode: string;
}

const DEFAULT_TERMS: BusinessTerminology = {
  products: "Products",
  product: "Product",
  inventory: "Inventory",
  customers: "Customers",
  customer: "Customer",
  sales: "Sales",
  sale: "Sale",
  pos: "Point of Sale",
  suppliers: "Suppliers",
  supplier: "Supplier",
  purchases: "Purchases",
  purchase: "Purchase",
  expenses: "Expenses",
  invoices: "Invoices",
  outstanding: "Outstanding",
  staff: "Staff",
  stores: "Stores",
  store: "Store",
  sectionCore: "Core",
  sectionSalesFinance: "Sales & Finance",
  sectionSupplyChain: "Supply Chain",
  productCategory: "Category",
  costPrice: "Cost Price",
  sellingPrice: "Selling Price",
  inStock: "In Stock",
  barcode: "Barcode",
};

// Business-type-specific terminology overrides
const TERMINOLOGY_MAP: Record<string, Partial<BusinessTerminology>> = {
  // Real Estate & Property
  real_estate_agency: {
    products: "Properties",
    product: "Property",
    inventory: "Listings",
    customers: "Clients",
    customer: "Client",
    sales: "Transactions",
    sale: "Transaction",
    pos: "Booking Desk",
    suppliers: "Developers",
    supplier: "Developer",
    purchases: "Acquisitions",
    purchase: "Acquisition",
    invoices: "Billing",
    outstanding: "Pending Payments",
    stores: "Branches",
    store: "Branch",
    sectionSupplyChain: "Acquisitions",
    productCategory: "Property Type",
    costPrice: "Purchase Price",
    sellingPrice: "Listing Price",
    inStock: "Available",
    barcode: "Property Code",
  },
  property_management: {
    products: "Units",
    product: "Unit",
    inventory: "Unit Register",
    customers: "Tenants",
    customer: "Tenant",
    sales: "Collections",
    sale: "Collection",
    pos: "Rent Desk",
    suppliers: "Contractors",
    supplier: "Contractor",
    purchases: "Maintenance Orders",
    purchase: "Maintenance Order",
    invoices: "Rent Invoices",
    outstanding: "Overdue Rent",
    expenses: "Maintenance Costs",
    stores: "Properties",
    store: "Property",
    sectionSalesFinance: "Rent & Finance",
    sectionSupplyChain: "Maintenance",
    productCategory: "Unit Type",
    costPrice: "Acquisition Cost",
    sellingPrice: "Monthly Rent",
    inStock: "Vacant",
    barcode: "Unit Code",
  },
  rental_apartments: {
    products: "Units",
    product: "Unit",
    inventory: "Room Register",
    customers: "Tenants",
    customer: "Tenant",
    sales: "Rent Collections",
    sale: "Collection",
    pos: "Reception",
    suppliers: "Service Providers",
    supplier: "Service Provider",
    purchases: "Service Orders",
    purchase: "Service Order",
    invoices: "Rent Invoices",
    outstanding: "Overdue Rent",
    expenses: "Operating Costs",
    stores: "Buildings",
    store: "Building",
    sectionSalesFinance: "Rent & Finance",
    sectionSupplyChain: "Services",
    productCategory: "Room Type",
    costPrice: "Cost",
    sellingPrice: "Monthly Rent",
    inStock: "Available",
    barcode: "Unit Number",
  },
  hotel_lodge: {
    products: "Rooms",
    product: "Room",
    inventory: "Room Inventory",
    customers: "Guests",
    customer: "Guest",
    sales: "Bookings",
    sale: "Booking",
    pos: "Front Desk",
    suppliers: "Vendors",
    supplier: "Vendor",
    purchases: "Supplies Orders",
    purchase: "Supply Order",
    invoices: "Guest Bills",
    outstanding: "Pending Bills",
    expenses: "Operating Costs",
    stores: "Locations",
    store: "Location",
    sectionSalesFinance: "Bookings & Finance",
    sectionSupplyChain: "Procurement",
    productCategory: "Room Type",
    costPrice: "Cost",
    sellingPrice: "Rate/Night",
    inStock: "Available",
    barcode: "Room Number",
  },

  // Automotive
  car_dealership: {
    products: "Vehicles",
    product: "Vehicle",
    inventory: "Fleet",
    customers: "Buyers",
    customer: "Buyer",
    sales: "Sales",
    sale: "Sale",
    pos: "Showroom",
    suppliers: "Dealers",
    supplier: "Dealer",
    purchases: "Acquisitions",
    purchase: "Acquisition",
    stores: "Showrooms",
    store: "Showroom",
    sectionSupplyChain: "Vehicle Sourcing",
    productCategory: "Vehicle Type",
    costPrice: "Purchase Price",
    sellingPrice: "Asking Price",
    inStock: "In Yard",
    barcode: "VIN / Chassis",
  },
  spare_parts: {
    products: "Parts",
    product: "Part",
    inventory: "Parts Stock",
    customers: "Clients",
    customer: "Client",
    suppliers: "Parts Dealers",
    supplier: "Parts Dealer",
    productCategory: "Part Category",
    barcode: "Part Number",
  },
  garage_workshop: {
    products: "Services",
    product: "Service",
    inventory: "Parts & Tools",
    customers: "Clients",
    customer: "Client",
    sales: "Job Cards",
    sale: "Job Card",
    pos: "Service Desk",
    suppliers: "Parts Suppliers",
    supplier: "Parts Supplier",
    purchases: "Parts Orders",
    purchase: "Parts Order",
    invoices: "Service Invoices",
    stores: "Workshops",
    store: "Workshop",
    productCategory: "Service Type",
    costPrice: "Parts Cost",
    sellingPrice: "Service Fee",
    inStock: "Available",
    barcode: "Job Code",
  },
  car_wash: {
    products: "Services",
    product: "Service",
    inventory: "Supplies",
    customers: "Clients",
    customer: "Client",
    sales: "Washes",
    sale: "Wash",
    pos: "Service Point",
    productCategory: "Wash Type",
    sellingPrice: "Service Fee",
  },
  motorcycle_dealer: {
    products: "Motorcycles",
    product: "Motorcycle",
    inventory: "Bike Stock",
    customers: "Buyers",
    customer: "Buyer",
    productCategory: "Bike Type",
    costPrice: "Purchase Price",
    sellingPrice: "Selling Price",
    inStock: "In Stock",
    barcode: "Engine Number",
  },
  tyre_battery: {
    products: "Products",
    product: "Product",
    productCategory: "Product Type",
    barcode: "Part Number",
  },

  // Food & Beverage
  restaurant: {
    products: "Menu Items",
    product: "Menu Item",
    inventory: "Kitchen Stock",
    customers: "Diners",
    customer: "Diner",
    sales: "Orders",
    sale: "Order",
    pos: "Order Terminal",
    suppliers: "Food Suppliers",
    supplier: "Food Supplier",
    purchases: "Supply Orders",
    purchase: "Supply Order",
    stores: "Outlets",
    store: "Outlet",
    productCategory: "Menu Category",
    costPrice: "Ingredient Cost",
    sellingPrice: "Menu Price",
    inStock: "Portions Available",
    barcode: "Item Code",
  },
  bakery: {
    products: "Baked Goods",
    product: "Baked Good",
    inventory: "Bakery Stock",
    customers: "Customers",
    customer: "Customer",
    sales: "Orders",
    sale: "Order",
    suppliers: "Ingredient Suppliers",
    supplier: "Ingredient Supplier",
    productCategory: "Product Type",
    costPrice: "Ingredient Cost",
    sellingPrice: "Price",
    inStock: "Available",
  },
  bar_lounge: {
    products: "Drinks & Menu",
    product: "Item",
    inventory: "Bar Stock",
    customers: "Patrons",
    customer: "Patron",
    sales: "Tabs",
    sale: "Tab",
    pos: "Bar Terminal",
    suppliers: "Beverage Distributors",
    supplier: "Distributor",
    productCategory: "Drink Category",
    costPrice: "Cost",
    sellingPrice: "Price",
    inStock: "In Stock",
  },
  butchery: {
    products: "Meat Products",
    product: "Meat Product",
    inventory: "Meat Stock",
    productCategory: "Cut Type",
    costPrice: "Buying Price",
    sellingPrice: "Selling Price/kg",
  },
  grocery: {
    products: "Produce",
    product: "Produce Item",
    inventory: "Fresh Stock",
    suppliers: "Farm Suppliers",
    supplier: "Farm Supplier",
    productCategory: "Produce Type",
  },
  fast_food: {
    products: "Menu Items",
    product: "Menu Item",
    inventory: "Kitchen Stock",
    sales: "Orders",
    sale: "Order",
    pos: "Order Counter",
    productCategory: "Menu Category",
    costPrice: "Cost",
    sellingPrice: "Price",
    inStock: "Servings",
  },
  water_beverages: {
    products: "Beverages",
    product: "Beverage",
    inventory: "Beverage Stock",
    customers: "Distributors",
    customer: "Distributor",
    productCategory: "Beverage Type",
  },

  // Health & Wellness
  pharmacy: {
    products: "Medicines",
    product: "Medicine",
    inventory: "Drug Stock",
    customers: "Patients",
    customer: "Patient",
    sales: "Dispensations",
    sale: "Dispensation",
    pos: "Dispensing Counter",
    suppliers: "Pharma Distributors",
    supplier: "Pharma Distributor",
    purchases: "Drug Orders",
    purchase: "Drug Order",
    stores: "Branches",
    store: "Branch",
    productCategory: "Drug Category",
    costPrice: "Wholesale Price",
    sellingPrice: "Retail Price",
    inStock: "In Stock",
    barcode: "Batch Number",
  },
  clinic: {
    products: "Services",
    product: "Service",
    inventory: "Medical Supplies",
    customers: "Patients",
    customer: "Patient",
    sales: "Consultations",
    sale: "Consultation",
    pos: "Reception",
    suppliers: "Medical Suppliers",
    supplier: "Medical Supplier",
    invoices: "Patient Bills",
    outstanding: "Unpaid Bills",
    productCategory: "Service Type",
    costPrice: "Cost",
    sellingPrice: "Fee",
  },
  gym_fitness: {
    products: "Memberships",
    product: "Membership",
    inventory: "Equipment",
    customers: "Members",
    customer: "Member",
    sales: "Subscriptions",
    sale: "Subscription",
    pos: "Front Desk",
    invoices: "Member Invoices",
    outstanding: "Overdue Fees",
    productCategory: "Plan Type",
    sellingPrice: "Monthly Fee",
    inStock: "Slots",
  },
  salon_barbershop: {
    products: "Services",
    product: "Service",
    inventory: "Supplies",
    customers: "Clients",
    customer: "Client",
    sales: "Appointments",
    sale: "Appointment",
    pos: "Reception",
    suppliers: "Product Suppliers",
    supplier: "Product Supplier",
    productCategory: "Service Type",
    costPrice: "Product Cost",
    sellingPrice: "Service Price",
  },
  spa: {
    products: "Treatments",
    product: "Treatment",
    inventory: "Supplies",
    customers: "Clients",
    customer: "Client",
    sales: "Sessions",
    sale: "Session",
    pos: "Reception",
    productCategory: "Treatment Type",
    sellingPrice: "Session Price",
  },

  // Agriculture
  agro_inputs: {
    products: "Farm Inputs",
    product: "Farm Input",
    inventory: "Input Stock",
    customers: "Farmers",
    customer: "Farmer",
    suppliers: "Manufacturers",
    supplier: "Manufacturer",
    productCategory: "Input Type",
  },
  farm_produce: {
    products: "Produce",
    product: "Produce Item",
    inventory: "Harvest Stock",
    customers: "Buyers",
    customer: "Buyer",
    sales: "Harvests Sold",
    sale: "Harvest Sale",
    productCategory: "Crop Type",
    costPrice: "Production Cost",
    sellingPrice: "Market Price",
    inStock: "Available (kg/bags)",
  },
  veterinary: {
    products: "Vet Products",
    product: "Vet Product",
    inventory: "Vet Stock",
    customers: "Farmers",
    customer: "Farmer",
    sales: "Treatments",
    sale: "Treatment",
    pos: "Dispensary",
    productCategory: "Product Type",
  },
  poultry_livestock: {
    products: "Livestock",
    product: "Animal",
    inventory: "Farm Stock",
    customers: "Buyers",
    customer: "Buyer",
    productCategory: "Animal Type",
    costPrice: "Rearing Cost",
    sellingPrice: "Selling Price",
    inStock: "Head Count",
  },
  agro_processing: {
    products: "Processed Goods",
    product: "Processed Good",
    inventory: "Mill Stock",
    productCategory: "Product Type",
    costPrice: "Processing Cost",
  },

  // Services
  printing_design: {
    products: "Services",
    product: "Service",
    inventory: "Materials",
    customers: "Clients",
    customer: "Client",
    sales: "Jobs",
    sale: "Job",
    pos: "Service Counter",
    productCategory: "Service Type",
    costPrice: "Material Cost",
    sellingPrice: "Service Fee",
  },
  laundry: {
    products: "Services",
    product: "Service",
    inventory: "Supplies",
    customers: "Clients",
    customer: "Client",
    sales: "Orders",
    sale: "Order",
    pos: "Drop-off Counter",
    productCategory: "Service Type",
    sellingPrice: "Price",
  },
  cleaning_services: {
    products: "Services",
    product: "Service",
    inventory: "Cleaning Supplies",
    customers: "Clients",
    customer: "Client",
    sales: "Jobs",
    sale: "Job",
    productCategory: "Service Type",
    sellingPrice: "Job Rate",
  },
  event_planning: {
    products: "Packages",
    product: "Package",
    inventory: "Event Supplies",
    customers: "Clients",
    customer: "Client",
    sales: "Events",
    sale: "Event",
    pos: "Booking Desk",
    productCategory: "Event Type",
    costPrice: "Event Cost",
    sellingPrice: "Package Price",
  },
  transport_logistics: {
    products: "Services",
    product: "Service",
    inventory: "Fleet",
    customers: "Clients",
    customer: "Client",
    sales: "Trips",
    sale: "Trip",
    pos: "Dispatch",
    suppliers: "Fuel Stations",
    supplier: "Fuel Station",
    purchases: "Fuel & Maintenance",
    purchase: "Expense",
    stores: "Depots",
    store: "Depot",
    productCategory: "Service Type",
    sellingPrice: "Trip Rate",
  },
  courier_delivery: {
    products: "Services",
    product: "Service",
    inventory: "Parcels",
    customers: "Senders",
    customer: "Sender",
    sales: "Deliveries",
    sale: "Delivery",
    pos: "Dispatch Counter",
    productCategory: "Delivery Type",
    sellingPrice: "Delivery Fee",
  },
  photography: {
    products: "Packages",
    product: "Package",
    inventory: "Equipment",
    customers: "Clients",
    customer: "Client",
    sales: "Sessions",
    sale: "Session",
    pos: "Booking Desk",
    productCategory: "Session Type",
    sellingPrice: "Session Fee",
  },
  ict_services: {
    products: "Services",
    product: "Service",
    inventory: "Equipment",
    customers: "Clients",
    customer: "Client",
    sales: "Jobs",
    sale: "Job",
    pos: "Service Desk",
    productCategory: "Service Type",
    costPrice: "Parts Cost",
    sellingPrice: "Service Fee",
  },
  tailoring: {
    products: "Designs",
    product: "Design",
    inventory: "Fabrics & Materials",
    customers: "Clients",
    customer: "Client",
    sales: "Orders",
    sale: "Order",
    pos: "Order Desk",
    suppliers: "Fabric Suppliers",
    supplier: "Fabric Supplier",
    productCategory: "Design Type",
    costPrice: "Material Cost",
    sellingPrice: "Price",
  },

  // Education
  school: {
    products: "Programs",
    product: "Program",
    inventory: "School Supplies",
    customers: "Students",
    customer: "Student",
    sales: "Enrollments",
    sale: "Enrollment",
    pos: "Registration",
    invoices: "Fee Invoices",
    outstanding: "Fee Arrears",
    expenses: "School Expenses",
    stores: "Campuses",
    store: "Campus",
    productCategory: "Program Type",
    sellingPrice: "Tuition Fee",
  },
  bookshop: {
    products: "Books",
    product: "Book",
    inventory: "Book Stock",
    productCategory: "Genre / Subject",
    barcode: "ISBN",
  },
  training_center: {
    products: "Courses",
    product: "Course",
    inventory: "Training Materials",
    customers: "Trainees",
    customer: "Trainee",
    sales: "Enrollments",
    sale: "Enrollment",
    pos: "Registration",
    productCategory: "Course Type",
    sellingPrice: "Course Fee",
  },

  // Wholesale & Distribution
  wholesale: {
    products: "Products",
    product: "Product",
    inventory: "Warehouse Stock",
    customers: "Retailers",
    customer: "Retailer",
    stores: "Warehouses",
    store: "Warehouse",
    productCategory: "Category",
    costPrice: "Wholesale Cost",
    sellingPrice: "Wholesale Price",
  },
  warehouse: {
    products: "Items",
    product: "Item",
    inventory: "Warehouse Stock",
    customers: "Clients",
    customer: "Client",
    stores: "Go-Downs",
    store: "Go-Down",
    productCategory: "Item Category",
  },
  import_export: {
    products: "Goods",
    product: "Good",
    inventory: "Cargo Stock",
    customers: "Trade Partners",
    customer: "Trade Partner",
    sales: "Shipments",
    sale: "Shipment",
    suppliers: "Foreign Suppliers",
    supplier: "Foreign Supplier",
    purchases: "Imports",
    purchase: "Import",
    productCategory: "Goods Category",
    costPrice: "CIF Price",
    sellingPrice: "Local Price",
  },

  // Finance & Energy
  forex_bureau: {
    products: "Currencies",
    product: "Currency",
    inventory: "Currency Stock",
    customers: "Clients",
    customer: "Client",
    sales: "Exchanges",
    sale: "Exchange",
    pos: "Exchange Counter",
    productCategory: "Currency Pair",
    costPrice: "Buying Rate",
    sellingPrice: "Selling Rate",
    inStock: "Available",
  },
  mobile_money: {
    products: "Services",
    product: "Service",
    inventory: "Float",
    customers: "Clients",
    customer: "Client",
    sales: "Transactions",
    sale: "Transaction",
    pos: "Agent Counter",
    productCategory: "Service Type",
  },
  fuel_station: {
    products: "Fuel Products",
    product: "Fuel Product",
    inventory: "Tank Levels",
    customers: "Customers",
    customer: "Customer",
    sales: "Pump Sales",
    sale: "Pump Sale",
    pos: "Pump Terminal",
    suppliers: "Fuel Distributors",
    supplier: "Fuel Distributor",
    productCategory: "Fuel Type",
    costPrice: "Depot Price",
    sellingPrice: "Pump Price",
    inStock: "Litres Available",
  },
  gas_dealer: {
    products: "Gas Products",
    product: "Gas Product",
    inventory: "Cylinder Stock",
    productCategory: "Cylinder Size",
    costPrice: "Buying Price",
    sellingPrice: "Selling Price",
    inStock: "Cylinders Available",
  },

  // Hardware & Construction
  hardware_shop: {
    products: "Hardware Items",
    product: "Hardware Item",
    inventory: "Hardware Stock",
    productCategory: "Item Category",
  },
  building_materials: {
    products: "Building Materials",
    product: "Building Material",
    inventory: "Materials Stock",
    customers: "Contractors",
    customer: "Contractor",
    productCategory: "Material Type",
  },
  paint_shop: {
    products: "Paints & Supplies",
    product: "Paint Product",
    inventory: "Paint Stock",
    productCategory: "Paint Type",
  },
  timber_yard: {
    products: "Timber Products",
    product: "Timber Product",
    inventory: "Timber Stock",
    productCategory: "Wood Type",
    inStock: "Pieces/Feet",
  },
  plumbing_electrical: {
    products: "Fittings & Supplies",
    product: "Fitting",
    inventory: "Fittings Stock",
    productCategory: "Fitting Type",
  },
};

export function useBusinessTerminology(): BusinessTerminology {
  const { businessId } = useAuth();

  const { data: businessType } = useQuery({
    queryKey: ["business-type", businessId],
    queryFn: async () => {
      if (!businessId) return null;
      const { data } = await supabase
        .from("businesses")
        .select("business_type")
        .eq("id", businessId)
        .single();
      return (data as any)?.business_type as string | null;
    },
    enabled: !!businessId,
    staleTime: 1000 * 60 * 30, // cache 30 min
  });

  return useMemo(() => {
    if (!businessType) return DEFAULT_TERMS;

    // Try direct match first
    const overrides = TERMINOLOGY_MAP[businessType];
    if (overrides) {
      return { ...DEFAULT_TERMS, ...overrides };
    }

    // Try to find by label match (for custom business types stored as label)
    const entry = Object.entries(TERMINOLOGY_MAP).find(([key]) => {
      const cat = BUSINESS_CATEGORIES_LOOKUP[key];
      return cat && cat.toLowerCase() === businessType.toLowerCase();
    });
    if (entry) {
      return { ...DEFAULT_TERMS, ...entry[1] };
    }

    return DEFAULT_TERMS;
  }, [businessType]);
}

// Lookup for matching stored labels back to keys
const BUSINESS_CATEGORIES_LOOKUP: Record<string, string> = {
  electronics: "Electronics & Gadgets",
  clothing_fashion: "Clothing & Fashion",
  supermarket: "Supermarket / Mini-mart",
  cosmetics_beauty: "Cosmetics & Beauty Products",
  shoes_accessories: "Shoes & Accessories",
  stationery_bookshop: "Stationery & Bookshop",
  kitchenware: "Kitchenware & Home Appliances",
  baby_kids: "Baby & Kids Store",
  jewelry: "Jewelry & Watches",
  general_merchandise: "General Merchandise",
  restaurant: "Restaurant / Café",
  bakery: "Bakery & Pastry Shop",
  bar_lounge: "Bar / Lounge / Pub",
  butchery: "Butchery / Meat Shop",
  grocery: "Grocery / Fresh Produce",
  fast_food: "Fast Food / Takeaway",
  water_beverages: "Water & Beverages Distributor",
  hardware_shop: "Hardware Shop",
  building_materials: "Building Materials",
  paint_shop: "Paint & Decorations Shop",
  timber_yard: "Timber Yard / Lumber",
  plumbing_electrical: "Plumbing & Electrical Supplies",
  car_dealership: "Car Dealership / Showroom",
  spare_parts: "Auto Spare Parts",
  garage_workshop: "Garage / Workshop",
  car_wash: "Car Wash",
  motorcycle_dealer: "Motorcycle / Boda-Boda Dealer",
  tyre_battery: "Tyre & Battery Shop",
  real_estate_agency: "Real Estate Agency",
  property_management: "Property Management",
  rental_apartments: "Rental Apartments / Hostels",
  hotel_lodge: "Hotel / Lodge / Guest House",
  pharmacy: "Pharmacy / Drug Shop",
  clinic: "Clinic / Medical Center",
  gym_fitness: "Gym / Fitness Center",
  salon_barbershop: "Salon / Barbershop",
  spa: "Spa & Massage",
  agro_inputs: "Agro Inputs / Farm Supplies",
  farm_produce: "Farm Produce / Harvest Sales",
  veterinary: "Veterinary / Animal Health",
  poultry_livestock: "Poultry & Livestock",
  agro_processing: "Agro Processing / Milling",
  printing_design: "Printing & Design Services",
  laundry: "Laundry / Dry Cleaning",
  cleaning_services: "Cleaning Services",
  event_planning: "Event Planning & Decoration",
  transport_logistics: "Transport & Logistics",
  courier_delivery: "Courier & Delivery",
  photography: "Photography / Studio",
  ict_services: "ICT / Computer Services",
  tailoring: "Tailoring / Fashion Design",
  school: "School / Academy",
  bookshop: "Bookshop / Learning Materials",
  training_center: "Training Center / Vocational",
  wholesale: "Wholesale Distributor",
  warehouse: "Warehouse / Go-Down",
  import_export: "Import & Export",
  forex_bureau: "Forex Bureau",
  mobile_money: "Mobile Money / Airtime Agent",
  fuel_station: "Fuel / Petrol Station",
  gas_dealer: "Gas / Cooking Gas Dealer",
};
